version: "3"

services:
  cep_configs:
    environment:
      - EVAL_PERIOD_SECS=30
      - COLLECTION_LIFETIME=5
      - DATA_CARRY_ENABLED=True
      - DATA_CARRY_WINDOW=5
      - QUERY_WITHIN_TIMEDELTA=250
      - MQTT_QOS_LEVEL=2

      - CP_RUNTIME_SECONDS=10
      - SIM_DURATION=1800
      - SERVER_QUERY_TYPE=4
      - IMAGE_FETCH_LIMIT=1
      - USE_HISTORIC_DIST_AFTER_N=0
      - CONSTRAINED_TTL=250
      - AGGREGATE_ENABLED=1
      - MIN_COST_AFTER_N_DIST=-1
      - ENFORCE_PRODUCTION_LOCATION=0
      - DIFFERENT_DEVICE_READ_PENATLY=2
      - DEVICE_CHANGE_PENALTY=5
      - DEVICE_NON_CHANGE_MULTIPLIER=4
      - MANIPULATE_CP_PARAMS=1
      - DIFFERENCE_BALANCE_WEIGHT=1
      - DIFFERENCE_EQUALIZER_WEIGHT=1
      - OPT_USE_CRR_VALUES_ONLY=1
      - MIN_REQUIRED_ACTIVE_VAR=10
      - RAW_IMAGE_SCALE_PERCENT=3
      - DEVICE_ACTION_LIMIT=6
      - DEVICE_ACTION_MIN_LIMIT=1
      - DEVICE_INTAKE_MIN_LIMIT=1
      - UTILIZE_PREFERRED_ACTION_COST=1
      - UTILIZE_PREFERRED_ACTION_LIMIT=105
      - USE_CUSTOM_COSTS=0
      - REPEAT_ON_NON_STAT=0
      - DATA_LOCALITY_WORKER_ACTION_LIMIT=2

      - RAW_PRODUCER_TYPES=1,1,1,3
      - RAW_OUTPUT_TOPIC_NAME=events.dist_1.input,events.heartbeat_1.input,events.road_1.input,events.image_1.input
      - RAW_OUTPUT_DATA_NAME=distance,beat,wifi,frame
      - RAW_OUTPUT_LENGTHS=1800,1800,1800,1800
      - RAW_OUTPUT_SLEEP_DURATIONS=1,1,1,1
      - RAW_OUTPUT_PER_MOMENT_COUNTS=5,5,5,5
      - RAW_PER_MOMENT_DIST_TYPES=7,7,8,8
      - RAW_OUTPUT_WINDOW_MIN_THRESHOLDS=5,5,5,1
      - RAW_OUTPUT_WINDOW_MAX_THRESHOLDS=5,5,5,5
      - RAW_OUTPUT_WINDOW_RANDOM_SEEDS=1337,1994,1105,1704
      - RAW_OUTPUT_WINDOW_DURATION=5,5,5,5
      - RAW_REQUIRED_AMOUNT_DIST_ACTIVE=1
      - RAW_REQUIRED_AMOUNT_L_THRESHOLD=1
      - RAW_REQUIRED_AMOUNT_H_THRESHOLD=1
      - RAW_REQUIRED_AMOUNT_WINDOW=10
      - PREFERRED_WINDOW_DIST_TYPE=1
      - RAW_EXPECTED_SENSOR_COST=10,10,10,100
      - RAW_OUTPUT_SIZE_MIN=55,55,55,55
      - RAW_OUTPUT_SIZE_MAX=125,125,125,125    